window.DAILY_COMPASS_RULES = {
  version: 4,
  dailyQuestCount: 3,
  priorities: [
    { id: "pokemon", label: "ポケモン活動", weight: 100 },
    { id: "youtube", label: "YouTube活動", weight: 92 },
    { id: "diet", label: "ダイエット", weight: 45 },
    { id: "ai", label: "AI", weight: 25 },
    { id: "recovery", label: "回復・娯楽", weight: 12 },
  ],
  dayTypes: {
    work: {
      label: "勤務日",
      note: "基本3クエスト。ポケモン/YouTubeだけで埋めず、支援枠にダイエットやAIも入れる。",
      slots: ["pokemon", "support", "youtube"],
      heavyLimit: 1,
    },
    mondayRest: {
      label: "月曜休み",
      note: "明確な休み。ポケモン/YouTubeの重めクエストが入りやすい。",
      slots: ["youtube", "pokemon", "support"],
      heavyLimit: 2,
    },
    childcareRest: {
      label: "育児あり休日",
      note: "勤務日より幅はあるが、長時間前提にはしない。",
      slots: ["pokemon", "youtube", "support"],
      heavyLimit: 1,
    },
    specialRest: {
      label: "特別休み・代休",
      note: "月曜休みに近い扱い。手動で選ぶ。",
      slots: ["youtube", "pokemon", "support"],
      heavyLimit: 2,
    },
  },
  categoryLabels: {
    pokemon: "ポケモン",
    youtube: "YouTube",
    diet: "ダイエット",
    ai: "AI",
    recovery: "回復",
  },
  weightLabels: {
    light: "軽め",
    medium: "普通",
    heavy: "重め",
  },
  generationRules: [
    "毎日見るのは3クエストだけ。ミニ習慣欄は作らない。",
    "優先順位はポケモン、YouTube、ダイエット、AI。",
    "勤務日も休日も3クエスト。ポケモン/YouTubeを軸にしつつ、支援枠でダイエットやAIも混ぜる。",
    "配信クエストは週2回を現実ラインにしつつ、配信同士は最低2日空ける。",
    "月4週のうち3週は配信集中、1週は配信1回+ショート1本の想定。",
    "入れ替えはジャンル固定なし。今日の3枠は維持する。",
    "完了・入れ替えの履歴はブラウザに保存し、Codexが更新するルールファイルとは分ける。",
  ],
  quests: [
    {
      id: "pokemon-battle",
      title: "ポケモンチャンピオンズを1戦する",
      categories: ["pokemon"],
      weight: "light",
      minutes: 15,
      frequency: "high",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "ポケモン活動を途切れさせないための基本クエスト。",
    },
    {
      id: "pokemon-video",
      title: "対戦動画を1本見る",
      categories: ["pokemon"],
      weight: "light",
      minutes: 15,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "環境理解や配信で使う話題につながるインプット。",
    },
    {
      id: "pokemon-article",
      title: "構築記事を1つ読む",
      categories: ["pokemon"],
      weight: "light",
      minutes: 10,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "気になる構築や流行を拾うための軽いインプット。",
    },
    {
      id: "pokemon-check-mon",
      title: "気になるポケモンを1体チェックする",
      categories: ["pokemon"],
      weight: "light",
      minutes: 10,
      frequency: "high",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "気になった理由や使い道を一言で整理する。配信で使うかまで決めなくてよい。",
    },
    {
      id: "pokemon-build",
      title: "構築を10分考える",
      categories: ["pokemon"],
      weight: "medium",
      minutes: 20,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "対戦力と配信内容の両方につながる普通クエスト。",
    },
    {
      id: "youtube-stream",
      title: "ポケモン配信をする",
      categories: ["youtube", "pokemon"],
      weight: "heavy",
      minutes: 60,
      frequency: "high",
      cooldownDays: 2,
      workdayLimitPerWeek: 1,
      weeklyDoneLimit: 2,
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "週2回を現実ラインにする主力クエスト。直近の配信から最低2日空ける。",
    },
    {
      id: "youtube-after-stream-note",
      title: "配信で使えそうな場面を1つメモする",
      categories: ["youtube"],
      weight: "light",
      minutes: 10,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "ショート/切り抜きにつなげる軽い後工程。",
    },
    {
      id: "youtube-small-improvement",
      title: "配信まわりの改善点を1つメモする",
      categories: ["youtube"],
      weight: "light",
      minutes: 10,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "配信する日でなくてもOK。話し方、時間帯、画面、次に軽くする工夫などを1行で残す。",
    },
    {
      id: "youtube-clip-candidate",
      title: "切り抜き候補を1つ選ぶ",
      categories: ["youtube"],
      weight: "medium",
      minutes: 20,
      frequency: "low",
      dayFit: ["mondayRest", "childcareRest", "specialRest"],
      detail: "配信できない週やショート週に入る候補。",
    },
    {
      id: "youtube-short",
      title: "ショート/切り抜きを1本作る",
      categories: ["youtube"],
      weight: "heavy",
      minutes: 45,
      frequency: "low",
      dayFit: ["mondayRest", "specialRest"],
      detail: "月1回程度の配信+ショート週で強めに出す重めクエスト。",
    },
    {
      id: "diet-strength",
      title: "筋トレを10〜15分する",
      categories: ["diet"],
      weight: "light",
      minutes: 15,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "毎日大事だが、3枠を埋めすぎない範囲で出す。",
    },
    {
      id: "diet-video",
      title: "ダイエット意識が上がる動画を1本見る",
      categories: ["diet"],
      weight: "light",
      minutes: 10,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "行動のスイッチを入れるための軽いタスク。",
    },
    {
      id: "diet-asken-log",
      title: "あすけんに食事を入力する",
      categories: ["diet"],
      weight: "light",
      minutes: 5,
      frequency: "medium",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "食事内容を完璧に記録しようとせず、意識を切らさないためにざっくり入力する。",
    },
    {
      id: "diet-weight",
      title: "体づくりの記録を1週間分見直す",
      categories: ["diet"],
      weight: "medium",
      minutes: 10,
      frequency: "low",
      dayFit: ["mondayRest", "childcareRest", "specialRest"],
      detail: "体重、筋トレ、動画視聴などをざっと見て、続いた要因か詰まった要因を1行で残す。",
    },
    {
      id: "ai-video",
      title: "AI関連動画を1本見る",
      categories: ["ai"],
      weight: "light",
      minutes: 15,
      frequency: "low",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "AIは低ウェイト。合間に触れるための軽いインプット。",
    },
    {
      id: "ai-question",
      title: "Codex/ChatGPTに投げる質問を1つ考える",
      categories: ["ai"],
      weight: "light",
      minutes: 10,
      frequency: "low",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "AIを現実の行動改善につなげる小さな実践。",
    },
    {
      id: "ai-review",
      title: "AIに相談した内容を1つ振り返る",
      categories: ["ai"],
      weight: "light",
      minutes: 10,
      frequency: "low",
      dayFit: ["work", "mondayRest", "childcareRest", "specialRest"],
      detail: "最近の相談や出力を見返して、次に使えそうなことを1行で残す。",
    },
    {
      id: "recovery-intentional-watch",
      title: "見たい動画やアニメを1本、意識して見る",
      categories: ["recovery"],
      weight: "light",
      minutes: 25,
      frequency: "low",
      dayFit: ["mondayRest", "childcareRest", "specialRest"],
      detail: "娯楽を敵にせず、満足感を残す回復枠。",
    },
  ],
};
